/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-emerald-500', 'bg-sky-400', 'bg-amber-400', 'bg-rose-400', 'bg-violet-400', 'bg-pink-400', 'bg-slate-400',
    'text-emerald-500', 'text-sky-400', 'text-amber-400', 'text-rose-400', 'text-violet-400', 'text-pink-400', 'text-slate-400'
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#6CD1FD", // changed from #00478d as requested
        "primary-container": "#005eb8",
        "on-primary-container": "#c8daff",
        "secondary": "#006970",
        "secondary-container": "#7af1fc",
        "on-secondary-container": "#006e75",
        "tertiary": "#3f484e",
        "background-light": "#f1f5f9",
        "background-dark": "#0f172a",
        "on-tertiary-container": "#d1dae1",
        "tertiary-fixed": "#dbe4eb",
        "primary-fixed": "#d6e3ff",
        "inverse-primary": "#a9c7ff",
        "on-tertiary-fixed": "#141d22",
        "surface-tint": "#005db6",
        "on-secondary-fixed": "#002022",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#bfc8ce",
        "primary-fixed-dim": "#a9c7ff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#3f484e",
        "outline": "#727783",
        "outline-variant": "#c2c6d4",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#5dd8e2",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#576066",
        "on-secondary-fixed-variant": "#004f54",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#7df4ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#00468c",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "background": "#f8f9ff",
        "on-surface-variant": "#424752",
        "surface-container": "#e5eeff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001b3d"
      },
      fontFamily: {
        "display": ["Manrope", "sans-serif"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg-mobile": ["Be Vietnam Pro"],
        "display-lg": ["Be Vietnam Pro"],
        "headline-sm": ["Be Vietnam Pro"],
        "headline-md": ["Be Vietnam Pro"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      },
      spacing: {
        "section-gap-desktop": "120px",
        "section-gap-mobile": "64px",
        "base": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
