export const ROUTES = {
  HOME: '/',
  PATIENT: {
    DASHBOARD: '/patient',
    METRICS: '/patient/metrics',
    APPOINTMENTS: '/patient/appointments',
    PRESCRIPTIONS: '/patient/prescriptions',
    MESSAGES: '/patient/messages',
    PROFILE: '/patient/profile',
  },
  DOCTOR: {
    DASHBOARD: '/doctor',
    ANALYTICS: '/doctor/analytics',
    APPOINTMENTS: '/doctor/appointments',
    MESSAGES: '/doctor/messages',
    PATIENTS: '/doctor/patients',
    PRESCRIPTIONS: '/doctor/prescriptions',
  },
  CLINIC: {
    DASHBOARD: '/clinic',
    REPORTS: '/clinic/reports',
    ALERTS: '/clinic/alerts',
    PATIENTS: '/clinic/patients',
    DOCTORS: '/clinic/doctors',
    ASSIGNMENT: '/clinic/assignment',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    CLINICS: '/admin/clinics',
    USERS: '/admin/users',
    SERVICES: '/admin/services',
    REPORTS: '/admin/reports',
    SETTINGS: '/admin/settings',
    AUDIT_LOGS: '/admin/audit-logs',
    SUPPORT: '/admin/support',
  },
  LOGIN: '/login',
};
